# Configuration spécifique à Déroulement Enseignement Service

# Server Port
server.port=8086

# Application Name
spring.application.name=deroulement-enseignement-service

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/daos_deroulement_enseignement_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger Configuration
springdoc.packages-to-scan=com.uasz.daos.deroulement.controller

# Logging
logging.level.com.uasz.daos.deroulement=DEBUG
