# Configuration spécifique à Maquette Service

# Server Port
server.port=8083

# Application Name
spring.application.name=maquette-service

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/daos_maquette_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger Configuration
springdoc.packages-to-scan=com.uasz.daos.maquette.controller

# Logging
logging.level.com.uasz.daos.maquette=DEBUG
