# Configuration commune à tous les microservices

# Actuator
management.endpoints.web.exposure.include=health,info,refresh
management.endpoint.health.show-details=always

# Logging par défaut
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.level.root=INFO